import { PrismicPreview } from '@prismicio/next'

import { Roboto } from 'next/font/google'
import './globals.css'

const roboto = Roboto({ subsets: ['latin'], weight: ["100", "300", "400", "500", "700", "900"] })

export const metadata = {
  title: 'Blog do Ramilson',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>{children}</body>
      <PrismicPreview repositoryName={'blog-ramils'} />
    </html>
  )
}
