import { PrismicPreview } from '@prismicio/next'
import { Fonts } from '../../custom/fonts';

import './globals.css'
import Footer from './common/footer';


export const metadata = {
  title: 'Blog do Ramilson',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${Fonts.roboto.variable} ${Fonts.roboto_serif.variable} bg-white`}>
        {children}
        <Footer />
      </body>
      <PrismicPreview repositoryName={'blog-ramils'} />
    </html>
  )
}
